FROM node:16.17.0-alpine

# Install FFmpeg
RUN apk --no-cache add ffmpeg

WORKDIR /app

COPY package*.json ./

RUN npm install 

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "startprod"]

