version: '3'

services:
  express-server:
    build: .
    container_name: express-server
    ports:
      - "3000:3000"
    environment:
      - OPENAI_API_KEY=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
      - Secret_Auth_Token=lyes
      - DB_HOST=mongo
    depends_on:
      - mongo

  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
     driver: local
 
