version: '3'

services:
  express-server:
    build: .
    container_name: express-server
    ports:
      - "3000:3000"
    environment:
      - OPENAI_API_KEY=put your own api key
      - Secret_Auth_Token=lyes
      - DB_HOST=mongo
    depends_on:
      - mongo
    volumes:
      - ./app/music:/app/music 

  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - /mnt/volume_tor1_01/mongodb:/data/db


volumes:
  mongodb_data:
     driver: local
  music:
 
