version: '3'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - OPENAI_API_KEY=randomherenotrealkey
      - Secret_Auth_Token=randomherenotrealkey
      - DB_HOST=mongo
    depends_on:
      - mongo

  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
     driver: local